#!/bin/sh
set -e

WORKDIR=`mktemp -d`
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR
cat <<EOF >buildtest.c
#include <stdio.h>

#include <zhuyin.h>

int main()
{
    zhuyin_context_t *ctx = zhuyin_init(SYSTEMDIR "/data", USERDIR);
    if (!ctx) {
        fprintf(stderr, "zhuyin_init() fails.\n");
        return -1;
    }
    zhuyin_fini(ctx);
    return 0;
}
EOF

touch $WORKDIR/user.conf

g++ -o buildtest buildtest.c \
    `pkg-config --cflags --libs libzhuyin` \
    -DSYSTEMDIR="\"`pkg-config --variable=pkgdatadir libzhuyin`\"" \
    -DUSERDIR="\"$WORKDIR\""
./buildtest
